# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'Dummies-Part1' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Dummies-Part1
pod 'RxCocoa'
pod 'RxSwift'
end
